version: '3'
services:
  api:
    build: ./
    command: npm start
    environment:
      - NODE_ENV=development
      - APP_PORT=3000
      - APP_HOST=0.0.0.0
      - JWT_SECRET=secret
    volumes:
      - ./:/home/node/sis-est-api-node-express
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sis-est-api-node-loopback_development
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
